import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

export interface ReportData {
  title: string;
  content: string;
  generatedAt: Date;
  metrics?: {
    revenue: number;
    expenses: number;
    cashFlow: number;
    runway: number;
  };
}

export function generatePDFReport(reportData: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(24)
         .fillColor('#2563eb')
         .text('VTA Insights', 50, 50);
      
      doc.fontSize(16)
         .fillColor('#64748b')
         .text('Financial Intelligence Report', 50, 80);

      // Title
      doc.fontSize(20)
         .fillColor('#1e293b')
         .text(reportData.title, 50, 120);

      // Generated date
      doc.fontSize(10)
         .fillColor('#64748b')
         .text(`Generated on ${reportData.generatedAt.toLocaleDateString()}`, 50, 150);

      // Metrics section if provided
      if (reportData.metrics) {
        doc.fontSize(14)
           .fillColor('#1e293b')
           .text('Key Metrics', 50, 180);

        const metrics = [
          { label: 'Total Revenue', value: `$${reportData.metrics.revenue.toLocaleString()}` },
          { label: 'Total Expenses', value: `$${reportData.metrics.expenses.toLocaleString()}` },
          { label: 'Net Cash Flow', value: `$${reportData.metrics.cashFlow.toLocaleString()}` },
          { label: 'Runway', value: `${reportData.metrics.runway} months` }
        ];

        let yPosition = 200;
        metrics.forEach(metric => {
          doc.fontSize(10)
             .fillColor('#64748b')
             .text(`${metric.label}: ${metric.value}`, 50, yPosition);
          yPosition += 20;
        });

        yPosition += 20;
      } else {
        yPosition = 180;
      }

      // Content
      doc.fontSize(12)
         .fillColor('#1e293b')
         .text(reportData.content, 50, yPosition, {
           width: 500,
           align: 'left'
         });

      // Footer
      doc.fontSize(8)
         .fillColor('#94a3b8')
         .text('Generated by VTA Insights - Financial Intelligence Platform', 50, doc.page.height - 50);

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
